In [1]:
from pathlib import Path
from dataloader.dataloader import Dataloader
from day_09.movie_theater import MovieTheater
import numpy as np

## Load and Parse Data

In [2]:
data = Dataloader(Path("day_09/input.csv")).data

red_tiles = []
for line in data:
    coordinates = []
    point = line.split(',')
    for coordinate in point:
        coordinates.append(int(coordinate))
    red_tiles.append(coordinates)

red_tiles = np.array(red_tiles)

## Create Movie Theater and Calculate Areas

In [3]:
movie_theater = MovieTheater(red_tiles)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [4]:
movie_theater.tile_matrix[movie_theater.tile_matrix == 2] = 1

In [5]:
x0, y0 = movie_theater.red_tiles[1]
x1, y1 = movie_theater.red_tiles[3]
matrix = movie_theater.tile_matrix[min(y0, y1):max(y0, y1)+1, min(x0, x1):max(x0, x1)+1]
print(matrix)


[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [8]:
new_max_area = 0
new_area_matrix = movie_theater.area_matrix.copy()
while new_max_area == 0:
# for i in range(2):
    max_idx = np.unravel_index(new_area_matrix.argmax(), new_area_matrix.shape)
    print("Max idx:", max_idx)

    first, second = max_idx
    x0, y0 = movie_theater.red_tiles[first]
    x1, y1 = movie_theater.red_tiles[second]

    if (movie_theater.tile_matrix[y0, x1] != 0) and (movie_theater.tile_matrix[y1, x0] != 0):
        matrix = movie_theater.tile_matrix[min(y0, y1):max(y0, y1)+1, min(x0, x1):max(x0, x1)+1]
        if np.where(matrix == 0)[0].size == 0:
            new_max_area = np.sum(matrix)

    new_area_matrix[(first,second)] = 0
    new_area_matrix[(second, first)] = 0



print("Max area:", new_max_area)
            

Max idx: (np.int64(63), np.int64(313))
Max idx: (np.int64(63), np.int64(311))
Max idx: (np.int64(63), np.int64(309))
Max idx: (np.int64(61), np.int64(313))
Max idx: (np.int64(61), np.int64(311))
Max idx: (np.int64(61), np.int64(309))
Max idx: (np.int64(63), np.int64(315))
Max idx: (np.int64(59), np.int64(313))
Max idx: (np.int64(61), np.int64(315))
Max idx: (np.int64(63), np.int64(317))
Max idx: (np.int64(57), np.int64(313))
Max idx: (np.int64(59), np.int64(311))
Max idx: (np.int64(61), np.int64(317))
Max idx: (np.int64(57), np.int64(311))
Max idx: (np.int64(63), np.int64(307))
Max idx: (np.int64(59), np.int64(315))
Max idx: (np.int64(57), np.int64(315))
Max idx: (np.int64(62), np.int64(313))
Max idx: (np.int64(57), np.int64(317))
Max idx: (np.int64(59), np.int64(317))
Max idx: (np.int64(63), np.int64(299))
Max idx: (np.int64(62), np.int64(311))
Max idx: (np.int64(63), np.int64(301))
Max idx: (np.int64(59), np.int64(309))
Max idx: (np.int64(61), np.int64(307))
Max idx: (np.int64(62), n

## Results

In [9]:
print(f"Part 1: area = {movie_theater.area_matrix.max()}")
print(f"Part 2: new area = {new_max_area.max()}")

Part 1: area = 4725826296
Part 2: new area = 1637556834
